# -*- coding: utf-8 -*-
"""Students' Social Media Addiction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ZVkKXA2oZBlTUvsSfyB9j5vAIAKs_2F
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns



#Loading Data

df = pd.read_csv("/content/Students Social Media Addiction.csv")

df.head()

# Summary stats for numeric columns

df.describe()



# Unique values for categorical columns

# Select categorical columns
cat_columns = df.select_dtypes(include='object').columns

# Show unique values for each categorical column
for col in cat_columns:
    print(f"--- {col} ---")
    print(df[col].unique())
    print()



#✅ Gender Distribution

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x="Gender", palette="pastel")
plt.title("gender distribution")
plt.xlabel("gender")
plt.ylabel("count")
plt.tight_layout()
plt.show()



#✅ Academic Level Distribution

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x="Academic_Level", palette="pastel")
plt.title("Academic Level Distributin")
plt.xlabel("Academic Level")
plt.ylabel("count")
plt.tight_layout()
plt.show()



#✅ Top 10 Most Used Platforms

plt.figure(figsize=(10, 5))
top_platforms = df["Most_Used_Platform"].value_counts().head(10)
sns.barplot(x=top_platforms.index, y=top_platforms.values, palette="viridis")
plt.title("Top 10 Most Used Platforms")
plt.xlabel("Platform")
plt.ylabel("Number of Users")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()



#✅ Correlation Heatmap

plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()



#1️⃣ Addiction Score vs Academic Performance

plt.figure(figsize=(10, 6))
sns.barplot(data = df, x="Affects_Academic_Performance", y="Addicted_Score", hue="Gender", estimator="mean")
plt.title("Addiction score vs Academic Performance")
plt.xlabel("Average Addicted Score")
plt.ylabel("Affects Academic Performance (Yes/No)")
plt.tight_layout()
plt.show()



#2️⃣ Addiction by Relationship Status

plt.figure(figsize=(8, 5))
sns.barplot(data=df, x='Relationship_Status', y='Addicted_Score', estimator='mean')
plt.title("Average Addiction Score by Relationship Status")
plt.ylabel("Average Addicted Score")
plt.xlabel("Relationship Status")
plt.tight_layout()
plt.show()















































